export const inputNames = [
  "out_dia",
  "bore_dia",
  "stack_height",
  "slot_depth",
  "slot_width",
  "slot_opening",
  "tooth_depth",
  "tooth_tipe_angle",
  "number_of_slot",
  "sfr1",
  "sfr2",
  "sfr3",
  "sfr4",
];
